/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import dto.FileDTO;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import static java.lang.Thread.sleep;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import threads.ReceiveFileThread;

/**
 *
 * @author TruongTN
 */
public class Server extends javax.swing.JFrame implements Runnable {

    ServerSocket serverReceiveFile = null;
    ObjectInputStream ois;
    File file = null;
    FileOutputStream fos;
    ReceiveFileThread receiveFile = null;
    Vector<FileDTO> fileList = new Vector<>();
    String filePath = "";
    boolean fileExist = false;
    Thread t;
    int start = 0;

    public Server() {
        try {
            initComponents();
            serverReceiveFile = new ServerSocket(12341);
            JOptionPane.showMessageDialog(null, "Server recieve file at the port: 12341");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMessage = new javax.swing.JTextArea();
        btnStart = new javax.swing.JButton();
        Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("File Path");

        jLabel2.setText("Message");

        jtaMessage.setEditable(false);
        jtaMessage.setColumns(20);
        jtaMessage.setRows(5);
        jtaMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtaMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtaMessageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtaMessageMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtaMessage);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(btnStart))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        JFileChooser fileChoosen = new JFileChooser();
//            fileChoosen.setCurrentDirectory(new java.io.File("."));
        fileChoosen.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChoosen.setAcceptAllFileFilterUsed(false);
        if (fileChoosen.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txtFilePath.setText(fileChoosen.getSelectedFile().getAbsolutePath());
            fileChoosen.cancelSelection();
            fileChoosen = new JFileChooser();
        }

    }//GEN-LAST:event_btnStartActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        if (txtFilePath.getText().trim().isEmpty() || txtFilePath.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Pleace choose a file in message");
            return;
        }
        if (this.jtaMessage.getText().trim().length() > 1) {
            try {
                System.out.println("Size: " + fileList.size());
                for (int i = start; i < fileList.size(); i++) {
                    file = new File(txtFilePath.getText().trim() + "\\" + fileList.get(i).fileName);
                    System.out.println(file.toString());
                    if (!file.exists()) {
                        fos = new FileOutputStream(file);
                        fos.write(fileList.get(i).data, 0, fileList.get(i).length);
                        start += 1;
                        JOptionPane.showMessageDialog(null, "Save file sucessful!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Please check directory again!");
                        return;
                    }         
                }
                fos.close();
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "File context is not exist!");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            jtaMessage.setText("");
        }

    }//GEN-LAST:event_SaveActionPerformed

    private void jtaMessageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtaMessageMousePressed
        
    }//GEN-LAST:event_jtaMessageMousePressed

    private void jtaMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtaMessageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtaMessageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaMessage;
    private javax.swing.JTextField txtFilePath;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                Socket fileClientServer = serverReceiveFile.accept();
                if (fileClientServer != null) {
                    sleep(400);
                    receiveFile = new ReceiveFileThread(fileClientServer, jtaMessage, fileList);
                    receiveFile.start();
                    fileExist = true;
                }
                sleep(500);
            } catch (Exception e) {

            }
        }
    }
}
